// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK6mpTVfntZVUeRojhQ7fHUGkttqXn1eY',
    appId: '1:650955623330:web:787386f554b00e59dec0fb',
    messagingSenderId: '650955623330',
    projectId: 'famdetecto',
    authDomain: 'famdetecto.firebaseapp.com',
    storageBucket: 'famdetecto.firebasestorage.app',
    measurementId: 'G-PVZBZHMPJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOwwbpka81oMcZHDWgJ-1Q-0E2u06TF50',
    appId: '1:650955623330:android:7385b4bc37f5c0d6dec0fb',
    messagingSenderId: '650955623330',
    projectId: 'famdetecto',
    storageBucket: 'famdetecto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLAypHLGpAzojxwRPmXrGt_Ss-FWMaD-0',
    appId: '1:650955623330:ios:5c83893d838f644bdec0fb',
    messagingSenderId: '650955623330',
    projectId: 'famdetecto',
    storageBucket: 'famdetecto.firebasestorage.app',
    iosBundleId: 'com.example.fammaize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLAypHLGpAzojxwRPmXrGt_Ss-FWMaD-0',
    appId: '1:650955623330:ios:5c83893d838f644bdec0fb',
    messagingSenderId: '650955623330',
    projectId: 'famdetecto',
    storageBucket: 'famdetecto.firebasestorage.app',
    iosBundleId: 'com.example.fammaize',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK6mpTVfntZVUeRojhQ7fHUGkttqXn1eY',
    appId: '1:650955623330:web:518294667888cefadec0fb',
    messagingSenderId: '650955623330',
    projectId: 'famdetecto',
    authDomain: 'famdetecto.firebaseapp.com',
    storageBucket: 'famdetecto.firebasestorage.app',
    measurementId: 'G-LP09WH68M5',
  );
}
